language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install: 
  - pip install --upgrade pip
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade codecov
install: 
  - pip install .
script: 
  - ls tests
  - cat tests/test_example.py
  - py.test
after_success:
  - codecov # submit coverage
